services:
  - type: web
    name: community-blog
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: COOKIE_SECURE
        value: "true"
